[package]
name = "bb8-redis"
version = "0.6.0"
authors = [
    "Dirkjan Ochtman <dirkjan@ochtman.nl>",
    "Daniel Smith <smith.daniel.br@gmail.com>",
    "Kyle Huey <khuey@kylehuey.com>"
]
description = "Full-featured async (tokio-based) redis connection pool (like r2d2)"
license = "MIT"
repository = "https://github.com/khuey/bb8"
edition = "2018"

[dependencies]
async-trait = "0.1"
bb8 = { version = "0.5.0", path = "../bb8" }
redis = { version = "0.18.1-alpha.0", default-features = false, features = ["cluster", "tokio-comp"] }

[dev-dependencies]
futures-util = "0.3"
tokio = { version = "0.3", features = ["macros"] }
